name: nuxt-story-telling-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      #- name: Run tests
        #run: npm test

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: docker build -t nuxt-story-telling .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name nuxt-story-telling-container nuxt-story-telling

      - name: Wait for container to be ready
        run: sleep 20

      - name: Check if app is running
        run: curl --fail http://localhost:3000 || (docker logs nuxt-story-telling-container && exit 1)
